name: sales_app
description: A new Flutter application.
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.86+86

environment:
  sdk: ">=2.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.17
  http: ^0.13.0
  cached_network_image: ^3.0.0
  fluttertoast: ^8.0.7
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  group_list_view: ^1.1.1
  local_auth: ^2.1.3
  dotted_border: ^2.0.0
  photo_view: ^0.14.0
  flutter_styled_toast: ^2.1.3
  liquid_pull_to_refresh: ^3.0.1
  dots_indicator: ^2.0.0
  lazy_load_scrollview: ^1.3.0
  image_picker: ^1.0.4
  easy_localization: ^3.0.1
  flutter_bloc: ^8.1.1
  equatable:
  date_format: ^2.0.2
  #intl:
  io: ^1.0.3
  mime: ^1.0.0
  image: ^3.3.0
  convert: ^3.1.1
  image_cropper: ^3.0.1
  flutter_otp_text_field: ^1.1.1
  otp_text_field: ^1.1.1
  signature: ^5.3.0
  html: ^0.15.0
 #image_gallery_saver: ^1.7.1
  flutter_pdfview: ^1.3.4
  dio: any
  permission_handler: ^10.2.0
  package_info: ^2.0.2
  url_launcher: ^6.1.8
  flutter_barcode_scanner: ^2.0.0
  store_redirect: ^2.0.1
  textfield_search: ^0.10.0
  sliding_switch: ^1.1.0
  device_info: ^2.0.3
  custom_searchable_dropdown: ^2.1.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  flutter_windowmanager: ^0.2.0
  store_checker: ^1.1.0
  dropdown_search: ^5.0.6
  searchfield: ^0.7.5
  foundation_flutter: ^0.2.0
  simple_barcode_scanner: ^0.0.8
  expansion_tile_card: ^2.0.0
  variable_app_icon: ^0.0.2
  open_file: ^3.3.2
  path_provider: ^2.0.12
  path: ^1.8.0
  #google_ml_kit:
  google_mlkit_text_recognition: ^0.13.0
  google_mlkit_barcode_scanning: ^0.11.0
  #google_mlkit_face_detection:
  #google_mlkit_commons:
  #camera_platform_interface:
  dependencies:
# huawei_hmsavailability: ^5.2.0+301
  http_proxy: ^1.1.0
  uni_links: ^0.5.1
  camera:
  flutter_webrtc: ^0.8.0
  flutter_document_picker: ^5.0.0
  uuid: ^4.1.0
  http_parser:
  gallery_saver: ^2.3.2
  crypto: ^3.0.3





dev_dependencies:
  flutter_test:
    sdk: flutter
  simple_animations: ^5.0.0+3
  swipable_stack: ^1.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - i18n/en-US.json
    - i18n/ar-AR.json
    - assets/images/
    - assets/images/login icon.png
    - lib/Views/HomeScreens/Subdealer/Menu/EKYC/images/barcode_scanner.png
    - lib/Views/HomeScreens/Subdealer/Menu/EKYC/images/sampleBarCode.png
    - lib/Views/HomeScreens/Subdealer/Menu/EKYC/images/arrowCoolDown.png
    - lib/Views/HomeScreens/Subdealer/Menu/EKYC/images/sanadIcon.png
    - lib/Views/HomeScreens/Subdealer/Menu/EKYC/images/jordanianBackID.png
    - lib/Views/HomeScreens/Subdealer/Menu/EKYC/images/jordanianFrontID.png
    - lib/Views/HomeScreens/Subdealer/Menu/EKYC/images/camera_video.png
    - lib/Views/HomeScreens/Subdealer/Menu/EKYC/images/jordanianPassport.png
    - lib/Views/HomeScreens/Subdealer/Menu/EKYC/images/personalNumber.png
    - lib/Views/HomeScreens/Subdealer/Menu/EKYC/images/temporaryPassport.png
    - lib/Views/HomeScreens/Subdealer/Menu/EKYC/images/IDFrame.png
    - lib/Views/HomeScreens/Subdealer/Menu/EKYC/images/PassportFrame.png
    - lib/Views/HomeScreens/Subdealer/Menu/EKYC/images/changePackage.png
    - lib/Views/HomeScreens/Subdealer/Menu/EKYC/images/unknown.png
    - lib/Views/HomeScreens/Subdealer/Menu/EKYC/images/documentLine.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
